
    create table tb_user (
       id int8 generated by default as identity,
        email varchar(150) not null,
        name varchar(150) not null,
        password varchar(32) not null,
        primary key (id)
    );

    alter table if exists tb_user 
       add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);

    alter table if exists tb_user 
       add constraint UK_jus3xa0l3009mkpbt9i5ilxx3 unique (name);
INSERT INTO tb_user(name, email, password) VALUES ('Abigail', 'aby@gmail.com', 'aby123');
INSERT INTO tb_user(name, email, password) VALUES ('Arthur', 'arthur@gmail.com', '123');
INSERT INTO tb_user(name, email, password) VALUES ('Nathanael', 'nate@gmail.com', 'nate123');
